"""Export project memory for agents that don't speak MCP (0.1.4).

`pjm export --claude-md` compiles the live memory — current decisions,
known gotchas, and the catalogue of already-failed approaches — into a
marked block inside CLAUDE.md (or .cursorrules with `--cursor`). Any agent
that reads the file inherits the project's judgment with zero MCP setup.

The block is bounded by markers and replaced in place on re-run; the rest
of the file is never touched. This complements (does not replace) the
`pjm init` bridge block, which carries MCP *instructions* — this block
carries memory *content*.
"""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

import typer

from projectmem.models import Event, location_to_file, superseded_ids
from projectmem.storage import read_events

MEMORY_START = "<!-- >>> projectmem memory (auto-generated, do not edit) >>> -->"
MEMORY_END = "<!-- <<< projectmem memory <<< -->"

FAILED_WINDOW_DAYS = 90
MAX_DECISIONS = 15
MAX_GOTCHAS = 10
MAX_FAILED = 12


def run(
    claude_md: bool = True,
    cursor: bool = False,
    stdout: bool = False,
    root: Path | None = None,
) -> None:
    root_path = root or Path.cwd()
    events = read_events(root)
    block = build_memory_block(events, root_path)

    if stdout:
        typer.echo(block)
        return

    targets: list[Path] = []
    if cursor:
        targets.append(root_path / ".cursorrules")
    if claude_md or not targets:
        targets.insert(0, root_path / "CLAUDE.md")

    for target in targets:
        _write_block(target, block)
        typer.echo(f"  {target.name}: projectmem memory block written.")


def build_memory_block(events: list[Event], root: Path) -> str:
    retired = superseded_ids(events)
    now = datetime.now(timezone.utc)

    # Live decisions only — superseded ones are history, not guidance.
    decisions = [
        e for e in events if e.type == "decision" and e.id not in retired
    ]

    # Stale flags annotate rather than exclude: a possibly-stale decision
    # is still the best current answer, the reader just deserves the flag.
    stale_ids: dict[str, str] = {}
    try:
        from projectmem.staleness import find_stale_events

        for item in find_stale_events(events, root):
            event = item["event"]
            if item["commits_since"] == -1:
                stale_ids[event.id] = "cited file no longer exists"
            else:
                stale_ids[event.id] = (
                    f"{item['file']} changed {item['commits_since']}x since"
                )
    except Exception:
        pass

    notes = [
        e for e in events
        if e.type == "note" and e.id not in retired
        # Snooze audit notes are bookkeeping, not project knowledge — they
        # belong in the log (auditable) but not in the exported gotchas.
        and not e.summary.startswith("precheck warnings snoozed")
    ]

    cutoff = now - timedelta(days=FAILED_WINDOW_DAYS)
    failed: list[Event] = []
    for e in events:
        if e.type != "attempt" or e.outcome != "failed":
            continue
        try:
            ts = datetime.fromisoformat(e.timestamp.replace("Z", "+00:00"))
        except (ValueError, AttributeError):
            continue
        if ts >= cutoff:
            failed.append(e)

    lines = [
        MEMORY_START,
        "## Project memory (projectmem)",
        "",
        f"_Generated by `pjm export` on {now.date().isoformat()}. "
        f"Re-run to refresh; do not edit by hand._",
        "",
        "### Current decisions",
    ]
    if decisions:
        for d in decisions[-MAX_DECISIONS:]:
            loc = f" `[{d.location}]`" if d.location else ""
            stale = (
                f" *(possibly stale — {stale_ids[d.id]})*" if d.id in stale_ids else ""
            )
            lines.append(f"- {d.summary}{loc}{stale}")
    else:
        lines.append("- None logged yet.")

    lines.extend(["", "### Known gotchas"])
    if notes:
        for n in notes[-MAX_GOTCHAS:]:
            loc = f" `[{n.location}]`" if n.location else ""
            lines.append(f"- {n.summary}{loc}")
    else:
        lines.append("- None logged yet.")

    lines.extend(["", "### Do NOT retry — these already failed"])
    if failed:
        by_file: dict[str, list[Event]] = defaultdict(list)
        for e in failed:
            file_path = (
                location_to_file(e.location) or e.location if e.location
                else (e.files[0] if e.files else "(general)")
            )
            by_file[file_path].append(e)
        count = 0
        for file_path, items in by_file.items():
            for e in items:
                if count >= MAX_FAILED:
                    break
                lines.append(f"- `{file_path}`: {e.summary}")
                count += 1
    else:
        lines.append(f"- No failed attempts in the last {FAILED_WINDOW_DAYS} days.")

    lines.extend(["", MEMORY_END])
    return "\n".join(lines)


def _write_block(target: Path, block: str) -> None:
    """Insert or replace the memory block, leaving the rest of the file alone."""
    if target.exists():
        content = target.read_text(encoding="utf-8")
        if MEMORY_START in content and MEMORY_END in content:
            start = content.index(MEMORY_START)
            end = content.index(MEMORY_END) + len(MEMORY_END)
            new_content = content[:start] + block + content[end:]
        else:
            new_content = content.rstrip("\n") + "\n\n" + block + "\n"
        target.write_text(new_content, encoding="utf-8")
        return
    header = "# CLAUDE.md\n\n" if target.name == "CLAUDE.md" else ""
    target.write_text(header + block + "\n", encoding="utf-8")
